---
title: "STA 160"
author: "Conner Pelletier"
date: "2023-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(matlib)
data = read.csv('heart_disease_health_indicators_BRFSS2015.csv')
```


```{r}
#Identify potential multicolinearity
library(corrplot)
corrplot(cor(data))
```


```{r}
#Histogram
library(ggplot2)
library(dplyr)
data %>% ggplot(aes(x = BMI, fill=as.factor(HeartDiseaseorAttack))) + geom_bar(position = "dodge")
```


```{r}
#recategorizing variables
data[data$Education == 1,]$Education = 0
data[data$Education == 2,]$Education = 0
data[data$Education == 3,]$Education = 0
data[data$Education == 4,]$Education = 1
data[data$Education == 5,]$Education = 1
data[data$Education == 6,]$Education = 1

data[data$BMI < 18.5,]$BMI = 1
data[18.5 <= data$BMI & data$BMI < 25,]$BMI = 2
data[25 <= data$BMI & data$BMI < 30,]$BMI = 3
data[data$BMI >= 30,]$BMI = 4

```


```{r}
#removing variables (MentHlth, PhysHlth, Income)
pop.cols = c(16, 17, 22)
data_new = data[-pop.cols]
```

Add new combinations here. Be sure to include the set of columns used in the combination into comb.mat
```{r}
#combining variables
data_new = transform(data_new, Y = paste(HeartDiseaseorAttack, Stroke))#combine 1, 7, into 20
data_new = transform(data_new, HighBPorChol = paste(HighBP, HighChol))#combine 2, 3, into 21 
data_new = transform(data_new, FruitsorVeggies = paste(Fruits, Veggies))#combine 10, 11, into 22
data_new = transform(data_new, SmokerorHvyAlcoholConsump = paste(Smoker, HvyAlcoholConsump)) #combine 6, 12, into 23
data_new = transform(data_new, GenHlthandEducation = paste(GenHlth, Education))#combine 15, 19, into 24
data_new = transform(data_new, DiabetesorDiffWalk = paste(Diabetes, DiffWalk))#combine 8, 16, into 25
data_new = transform(data_new, SmokerorBMI = paste(Smoker, BMI))#combine 5, 6, into 26

comb.mat = rbind(c(1, 7, 20), c(2, 3, 21), c(10, 11, 22), c(6, 12, 23), c(15, 19, 24), c(8, 16, 25), c(5, 6, 26))

```


```{r}
#Gender/Age/Health stat table/heatmap
#represents plain p(y==1) now, can change stat to any single number for each population
sex_genhlth_age_table <- function(data, sex){
  table = sapply(1:13, FUN = function(c){
    col = sapply(1:5, FUN = function(r){
      sub = data[which(data$Age == c),] 
      sub = sub[which(sub$GenHlth == r),]
      sub = sub[which(sub$Sex == sex),]
      stat = sum(sub$HeartDiseaseorAttack)/length(sub$HeartDiseaseorAttack)
      return(stat)
    })
    return(col)
  })
  colnames(table) = 1:13
  rownames(table) = 1:5
  return(table)
}
test_table1 = sex_genhlth_age_table(data, sex = 1)
test_table2 = sex_genhlth_age_table(data, sex = 0)
par(mfrow = c(1, 2))
heatmap(test_table1, Rowv=NA, Colv=NA, col = terrain.colors(256))
heatmap(test_table2, Rowv=NA, Colv=NA, col = terrain.colors(256))
par(mfrow = c(1, 1))
```



```{r}
get.inputs <- function(){
  Age <- readline(prompt="Enter your age: ")
  Sex <- readline(prompt= "Enter your sex (please enter 'male' or 'female'):")
  GenHlth <- readline(prompt="Rate your general health from 1-5 (1 being good, 5 being bad):")
  
  if(Age<=25) {
    Age = 1
  } else if(Age<=30) {
    Age = 2
  } else if(Age<=35) {
    Age = 3
  } else if(Age<=40) {
    Age = 4
  } else if(Age<=45) {
    Age = 5
  } else if(Age<=50) {
    Age = 6
  } else if(Age<=55) {
    Age = 7
  } else if(Age<=60) {
    Age = 8
  } else if(Age<=65) {
    Age = 9
  } else if(Age<=70) {
    Age = 10
  } else if(Age<=75) {
    Age = 11
  } else if(Age<=80) {
    Age = 12
  } else{
    Age = 13
  }
  
  if(Sex == 'male'){
    Sex = 0
  } else if(Sex == 'female'){
    Sex = 1
  }
  
  GenHlth = as.integer(GenHlth)
    return(c(Sex, Age, GenHlth))
}
SAG = get.inputs()
```


```{r}
get.maxes <- function(data, Sex, Age, GenHlth){
  ##list of increase in p(Y = 1) for each category of each X
  list <- sapply(2:ncol(data), FUN = function(Xcol){
    sub = data[which(data$Age == Age),] 
    sub = sub[which(sub$GenHlth == GenHlth),]
    sub = sub[which(sub$Sex == Sex),]
    null.prob = sum(sub$HeartDiseaseorAttack)/length(sub$HeartDiseaseorAttack)
    X.categories = unique(data[,Xcol])
    ##Gets P(Y=1|x=age,sex,hlth,X) for all categories in X 
    new.probs = sapply(1:length(X.categories), FUN = function(i){
      #super.sub is hypothetical subset for specific category in X
      super.sub = sub[sub[,Xcol] == X.categories[i],]
      prob = sum(super.sub$HeartDiseaseorAttack[])/length(super.sub$HeartDiseaseorAttack)
      names(prob) = X.categories[i]
      return(prob)
    })
    diff = new.probs - null.prob
    return(diff)
  })
  
  #Naming
  names(list) = colnames(data[,2:ncol(data)])
  pop = c(which(names(list) == 'Sex'), which(names(list) == 'Age'), which(names(list) == 'GenHlth'), which(names(list) == 'Y'))
  list = list[-pop]
  maxes = sapply(1:length(list), FUN = function(i){
    max = max(list[[i]])
    names(max) = paste(names(list[i]), names(list[[i]][list[[i]] == max]), sep = ": ")[1]
    return(max)
    })
  
  return(maxes[order(maxes, decreasing=TRUE)[1:5]])
}
get.maxes(data, 1, 1, 4)
```


```{r}

data.mat <- lapply(0:1, FUN = function(s){
  list <- lapply(1:13, FUN = function(a){
    maxes <- lapply(1:5, FUN = function(gh){
      max = get.maxes(data_new[,c(-7, -20)], s, a, gh)[1]
      list = list(max[[1]], names(max), s, a, gh)
      return(list)
    })
    maxes = do.call(rbind, maxes)
    return(maxes)
  })
  list = do.call(rbind, list)
  return(list)
})
risk = data.frame(do.call(rbind, data.mat))
colnames(risk) = c("Max Difference", "Category", "Sex", "Age", "GenHlth")
```





```{r}
risk$`Max Difference` = as.numeric(risk$`Max Difference`)
risk$`Category` = as.character(risk$`Category`)
risk$`Age` = as.numeric(risk$`Age`)
risk$`Sex` = as.numeric(risk$`Sex`)
risk$`GenHlth` = as.numeric(risk$`GenHlth`)
write.csv(risk, file = "Risk_Factors.csv")
```

```{r}

Risk.Factors <- function(data){
  SAG = get.inputs()
  return(get.maxes(data, SAG[1], SAG[2], SAG[3]))
}

Risk.Factors(data_new)
```




```{r}
library(ggplot2)
library(reshape2)
plot.cols.density <- function(many.boot, value_name){
  w.plot <- melt(many.boot)
  w.plot <- w.plot[,-1]
  #colnames(w.plot) = c("Variable", value_name)

  p <- ggplot(aes(x=value, colour=Var2), data=w.plot)
  
  return(p + geom_density() + labs(x = value_name, color = 'Comparison'))
}
plot.cols.density(boot.ent.bivar.1(data_new, indexY = 20, indexX = 23), 'Entropy')

```


```{r}
boot.ent.bivar.1 <- function(data, indexY, indexX, og.data = NULL){
  B = 500
  rownum = length(unique(og.data[,indexY]))
  colnum = length(unique(og.data[,indexX]))
  many.boot.theta = t(sapply(1:B, function(x){
    N =5000
    boot.sample.index = sample(nrow(data), N, replace = TRUE)
    boot.data = data[boot.sample.index,]
    boot.table = table(boot.data[,c(indexX, indexY)])
    if(nrow(boot.table) != rownum){
      boot.table = rbind(boot.table, rep(0, ncol(boot.table)))
    } 
    if (ncol(boot.table) != colnum){
      boot.table = cbind(boot.table, rep(0, nrow(boot.table)))
    }
    boot.table[boot.table == 0] = 0.000001
    
    Py = colSums(boot.table)/N
    #Probability vector of all categories of Y (columns)
    Pxi = t(t(boot.table)%*%(diag(1/colSums(t(boot.table)))))
    #Conditional Probability vectors for categories of Y(columns) given each category in x    (rows)
    CondEntNull = -t(Py)%*%log(Py)
    CondEntX = sapply(1:nrow(Pxi), FUN = function(i){
      temp = -t(Pxi[i,])%*%log(Pxi[i,])
      return(temp*rowSums(boot.table)[i])
    })
    CondEntVec = c(CondEntNull, sum(CondEntX)/N)
    diff = CondEntVec[1]-CondEntVec[2]
    names(diff) = paste('Y',colnames(boot.data)[indexX], sep = " vs ")
    return(diff)
  }))
  return(many.boot.theta)
}

boot.ent.bivar.1(sub, 20, 4, og.data = data_new)
```

```{r}
sub = data_new[which(data$Age == 1),] 
sub = sub[which(sub$GenHlth == 4),]
sub = sub[which(sub$Sex == 1),]
pop = c(which(colnames(sub) == 'Sex'), which(colnames(sub) == 'Age'), which(colnames(sub) == 'GenHlth'))
sub = sub[,-pop]

N =5000
boot.sample.index = sample(nrow(sub), N, replace = TRUE)
boot.data = sub[boot.sample.index,]
boot.table = table(boot.data[,c(5, 17)])
rownum = length(unique(data_new[,5]))
colnum = length(unique(data_new[,17]))
if(nrow(boot.table) != rownum){
  rbind(boot.table, rep(0, ncol(boot.table)))
}
if (ncol(boot.table) != colnum){
  cbind(boot.table, rep(0, nrow(boot.table)))
}
boot.table[boot.table == 0] = 0.000001
```

  
```{r}
boot.ent.bivar.2 <- function(data, indexY, indexX, comb.set){
  ##2-way interaction comparison (3 diffs)
  B = 500
  many.boot.theta = t(sapply(1:B, function(x){
    N = 5000
    diffs = sapply(1:length(comb.set), FUN = function(c){
      boot.sample.index = sample(nrow(data), N, replace = TRUE)
      boot.data = data[boot.sample.index,]
      boot.table = table(boot.data[,c(comb.set[c], indexY)])
      boot.table[boot.table == 0] = 0.0001
      Py = colSums(boot.table)/N
      #Probability vector of all categories of Y (columns)
      Pxi = t(t(boot.table)%*%(diag(1/colSums(t(boot.table)))))
      #Conditional Probability vectors for categories of Y(columns) given each category   in x      (rows) 
      CondEntNull = -t(Py)%*%log(Py)
      CondEntXi = sapply(1:nrow(Pxi), FUN = function(i){
        EntXi = -t(Pxi[i,])%*%log(Pxi[i,])
        return(EntXi*rowSums(boot.table)[i])
      })
      CondEntVec = c(CondEntNull, sum(CondEntXi)/N)
      diff = CondEntVec[1]-CondEntVec[2]
      names(diff) = paste('Y', colnames(boot.data)[comb.set[c]], sep = ' vs ')
      return(diff) 
    })
    return(diffs)
  }))
}

```



```{r}
#bootstrap distributions for conditional entropy
library(dplyr)
entropy.pdf.bivar <- function(data, indexY, indexX, comb.mat){
  #Determine if more X should be considered
  if(indexX %in% comb.mat[,3]){
    comb.set = comb.mat[which(comb.mat[,3] == indexX),]
    ##Generate bootstrap Conditional Entropy distribution for relevant X and Y
    many.boot.stat = boot.ent.bivar.2(data, indexY, indexX, comb.set)
    ##PLOT
    many.boot.stat = na.omit(many.boot.stat)
    print(plot.cols.density(many.boot.stat, "Entropy"))
  }else{
    comb.set = indexX
    ##Generate bootstrap Conditional Entropy distribution for relevant X and Y
    many.boot.stat = boot.ent.bivar.1(data, indexY, indexX)
    ##PLOT
    many.boot.stat = na.omit(many.boot.stat)
    print(plot.cols.density(many.boot.stat, "Entropy"))
  }
  return()
}

#entropy.pdf.bivar(data = data_new, indexY = 20, indexX = 24, comb.mat = comb.mat)
```

```{r}
#Plots all combined variables

sapply(21:26, FUN = function(x){
  entropy.pdf.bivar(data = data_new, indexY = 20, indexX = x, comb.mat = comb.mat)
})

```



```{r}
get.max.CondEntX <- function(data, Sex, Age, GenHlth, Y_name){
  ##list of increase in p(Y = 1) for each category of each X
  sub = data[which(data$Age == Age),] 
  sub = sub[which(sub$GenHlth == GenHlth),]
  sub = sub[which(sub$Sex == Sex),]
  pop = c(which(colnames(sub) == 'Sex'), which(colnames(sub) == 'Age'), which(colnames(sub) == 'GenHlth'))
  sub = sub[,-pop]
  Ycol = which(colnames(sub) == Y_name)
  
  ##CHANGE THIS TO INCLUDE ONLY BINARY OR ONLY MULTIVARIATE
  Xcols = c(1:ncol(sub))[-c(1, 7, Ycol)]
  
  mean.entropy.all = sapply(Xcols, FUN = function(i){
    boot.ent = boot.ent.bivar.1(sub, indexY = Ycol, indexX = i, og.data = data)
    mean = mean(boot.ent)
    names(mean) = colnames(boot.ent)[1]
    return(mean)
  })
  
  return(mean.entropy.all[order(mean.entropy.all, decreasing=TRUE)])
}

#get.max.CondEntX(data_new, 1, 1, 4, "Y")
```

```{r}
data.mat.ent <- lapply(0:1, FUN = function(s){
  list <- lapply(1:13, FUN = function(a){
    maxes <- lapply(1:5, FUN = function(gh){
      max = get.max.CondEntX(data_new, s, a, gh, "Y")[1]
      list = list(max[[1]], names(max), s, a, gh)
      return(list)
    })
    maxes = do.call(rbind, maxes)
    return(maxes)
  })
  list = do.call(rbind, list)
  return(list)
})
df.ent = data.frame(do.call(rbind, data.mat.ent))
colnames(df.ent) = c("Max Mutual Info", "Comparison", "Sex", "Age", "GenHlth")

df.ent$`Max Mutual Info` = as.numeric(df.ent$`Max Mutual Info`)
df.ent$`Comparison` = as.character(df.ent$`Comparison`)
df.ent$`Age` = as.numeric(df.ent$`Age`)
df.ent$`Sex` = as.numeric(df.ent$`Sex`)
df.ent$`GenHlth` = as.numeric(df.ent$`GenHlth`)
write.csv(df.ent, file = "Risk_Factors_Entropy.csv")
```

